image: rafaribe/pulumi-ci:1
stages:
  - build
variables:
  PULUMI_HOME: '$CI_PROJECT_DIR'
before_script:
  - npm install
  - pulumi login -l
  - pulumi stack init ${CI_COMMIT_REF_NAME}
build_auto:
  stage: build
  script:
    - pulumi stack select ${CI_COMMIT_REF_NAME}
    - pulumi up -y --stack ${CI_COMMIT_REF_NAME}
  only:
    - master
