image: rafaribe/pulumi-ci:1
stages:
  - build
variables:
  PULUMI_HOME: '$CI_PROJECT_DIR'
before_script:
  - npm install
  - pulumi stack init 'test'
build_auto:
  stage: build
  script:
    - pulumi up --stack ${CI_COMMIT_REF_NAME} --non-interactive
  environment:
    name: ${CI_COMMIT_REF_NAME}
  only:
    - master
